#!/usr/bin/env python3
"""Replace the 27 auto-derived acceptance walkthroughs (E02/E03/E04) in
data/intents.json with concrete, reviewer-walkable scenarios. Idempotent:
matches by intent id; leaves all other fields untouched."""
import json, pathlib, sys

PROJ = pathlib.Path("/Users/nfilho/claude/Scopezilla/DATAPREV-PAT")
INTENTS = PROJ / "data" / "intents.json"

NEW = {
"INT-019": "A analista de RH da Construtora Alfa (CNPJ 12.345.678/0001-90), autenticada via gov.br, abre \"Nova demanda\", informa 320 trabalhadores, valor-face R$ 44,00/dia, 22 dias/mês, modalidade PAT e janela de vigência de 7 dias. Ao salvar, o revisor confirma que foi criada uma Opportunity nativa do Sales Cloud vinculada à Account da Alfa, com todos esses parâmetros preenchidos e status \"Aberta para propostas\". Inspecionando a Opportunity e a Account, o revisor confirma que nenhum CPF foi gravado — apenas o CNPJ e uma referência tokenizada resolvida em runtime (ADR 0001).",
"INT-020": "Alelo, Ticket e VR submetem, cada uma por chamada de API autenticada, uma proposta para a Opportunity aberta da Alfa (MDR de 2,8%, 3,1% e 3,6% respectivamente). O revisor confirma que cada submissão criou uma Quote nativa associada à Opportunity, sem nenhuma sessão de UI nem licença de portal consumida pela facilitadora. Ao tentar, pela API de uma facilitadora, ler as Quotes das outras, o revisor confirma que a resposta não expõe nenhuma proposta concorrente (equidade por construção).",
"INT-021": "Durante a janela de 7 dias, o revisor acompanha a demanda receber as Quotes; logado como a beneficiária, vê as 3 Quotes recebidas mas confirma que a ação de seleção está indisponível. No fechamento da janela (D+7) o estado transita para \"Em seleção\" e só então a seleção é liberada. O revisor confirma que nenhuma seleção foi possível antes do fechamento da janela.",
"INT-022": "Com a janela fechada e 3 Quotes recebidas, a beneficiária abre a tela Comparar Propostas e vê as três lado a lado — MDR, prazo de repasse e valor normalizado por trabalhador na mesma unidade. O revisor confirma o alinhamento dos atributos decisórios para comparação justa e que a ação de selecionar permanece desabilitada enquanto a janela não tiver fechado.",
"INT-023": "A beneficiária seleciona a Quote da Ticket (MDR 3,1%) e informa a justificativa \"melhor prazo de repasse\". O revisor confirma que a demanda transita para \"Contrato firmado\", a Quote vencedora fica marcada, as demais como \"Não selecionadas\" e a justificativa fica registrada na trilha — transição só possível após o fechamento da janela.",
"INT-024": "A facilitadora Ticket anexa o PDF do contrato firmado com a Alfa. O revisor confirma que o arquivo fica vinculado ao contrato como versão 1, imutável, com metadados (data, partes, vigência). A facilitadora sobe um aditivo e o revisor confirma que ele entra como versão 2 preservando a versão 1, e que não há redline, biblioteca de cláusulas, obrigações nem assinatura eletrônica (sem CLM no MVP).",
"INT-025": "Após o contrato firmado, a beneficiária classifica por CNPJ e por matriz/filial os trabalhadores acima e abaixo de 5 salários mínimos (matriz /0001-90 → 210 abaixo / 40 acima; filial /0002-71 → 60 abaixo / 10 acima). Ao confirmar o termo de aceite, o revisor confirma que a classificação é integrada ao Novo PAT via INIS PJ e que ela usa CNPJ + faixa salarial — nenhum CPF de trabalhador é gravado (ADR 0001).",
"INT-026": "A Construtora Alfa (PAT) e a Boutique Beta (não-PAT) contratam pela mesma plataforma. O revisor confirma que, para a Alfa, o cálculo aplica o teto de 3,6% e o benefício fiscal do PAT; para a Beta, o mesmo fluxo roda sem o benefício fiscal. Ele confirma que o benefício fiscal nunca é aplicado à beneficiária não-PAT.",
"INT-027": "O time de migração carrega um lote de 500 contratos legados. Amostrando 5 registros, o revisor confirma que cada um foi mapeado à estrutura nativa Account/Opportunity/Quote com o PDF anexado e os metadados (vigência, MDR, facilitadora), e que nenhum CPF foi persistido — as referências de PF vêm tokenizadas (ADR 0001).",
"INT-028": "O restaurante Sabor & Cia (CNPJ 98.765.432/0001-10), autenticado como PJ via gov.br, faz o autocadastro no portal uma única vez. O revisor confirma que a plataforma cria um registro pendente na base nacional unificada de estabelecimentos e que não há recredenciamento facilitadora a facilitadora. Ele confirma que o CPF do representante não é persistido fora da fronteira do ADR 0001 — a identidade PF é resolvida em runtime.",
"INT-029": "O Sabor & Cia acessa seu registro pendente e vê um checklist do que falta (licença sanitária, comprovação de regularidade fiscal) e sobe os dois documentos. O revisor confirma que ficam anexados ao registro, o checklist marca os itens recebidos e explica por que o cadastro segue pendente, e que o registro não avança para análise humana enquanto o conjunto mínimo de documentos não estiver completo.",
"INT-030": "Completo o checklist, a plataforma roda as regras determinísticas: CNPJ ativo na Receita, CNAE compatível com alimentação e documentos legíveis/íntegros. Para o Sabor & Cia (tudo conforme), o revisor confirma que o caso é resolvido automaticamente; para um segundo estabelecimento com CNAE incompatível, confirma que o caso é transbordado para análise humana. Ele confirma que nenhum documento sinalizado para análise é aprovado automaticamente.",
"INT-031": "A Analista MTE Regina abre o registro transbordado no console, marca cada documento como Válido ou Inválido com motivo e emite o parecer \"Exigência complementar\", pedindo a licença atualizada. O revisor confirma que toda a operação fica na trilha de auditoria e que o sistema não permite parecer \"Deferido\" com documento pendente ou marcado Inválido sem justificativa registrada.",
"INT-032": "A facilitadora Alelo aprova o Sabor & Cia na sua relação; meses depois, o MTE descredencia o estabelecimento do programa por irregularidade. O revisor confirma que cada mudança de status é registrada e que o estado consultável na base de estabelecimentos passa a \"descredenciado\" (lido pelo adquirente antes de transacionar). Ele confirma que a plataforma não descredencia por conta própria — a ação legal é da facilitadora/MTE; a plataforma registra e propaga.",
"INT-033": "O Sabor & Cia envia a licença sanitária emitida pela prefeitura de Recife. O revisor confirma que a IA extrai a data de validade (31/12/2026) e a preenche no registro. Para uma licença de layout atípico com baixa confiança de extração, ele confirma que o campo fica sinalizado para confirmação e que o analista precisa validar o valor antes de ele ser tratado como confirmado.",
"INT-034": "Para um estabelecimento com licença válida até 31/12/2026, o revisor confirma que a plataforma dispara alertas com antecedência (60 e 30 dias antes) e conduz o fluxo de renovação. Avançando a data de simulação para depois do vencimento sem renovação analisada, ele confirma que o estabelecimento não é marcado como apto — a aptidão só se mantém com renovação analisada.",
"INT-035": "A Construtora Alfa envia o CSV da folha da competência 08/2026 (320 linhas) pelo portal. O revisor confirma que ela recebe confirmação de recebimento em segundos, a sessão não trava e o arquivo entra numa fila de processamento assíncrona. Ele confirma que a crítica não roda de forma síncrona no clique do upload (o pico de ~28/s excederia o teto de 25 Apex longos concorrentes).",
"INT-036": "Uma folha enfileirada com o layout correto passa na checagem de integridade estrutural e segue para disponibilização à facilitadora; uma segunda folha com coluna faltando é sinalizada à beneficiária com o motivo (\"coluna valor_diario ausente\"). O revisor confirma que nenhuma linha de folha é persistida em qualquer dos casos.",
"INT-037": "Uma folha aprovada na validação estrutural recebe a crítica automática por IA (consistência dos dados da competência) executada de forma assíncrona. O revisor confirma que o resultado da crítica alimenta a liberação para download pela facilitadora e que a crítica não roda no clique do upload.",
"INT-038": "O revisor inspeciona o schema e confirma a existência dos objetos custom: folha por competência (somente cabeçalho — contrato, competência mês-ano, totais), contrato/vigência e regras de split parametrizáveis, todos sobre a base Sales Cloud. Ele confirma que não há Revenue Cloud e que não há linha de item de folha persistida (header/competência apenas).",
"INT-039": "A facilitadora Ticket baixa via API a folha íntegra do contrato da Alfa referente à competência 08/2026 e devolve status \"processado\" com valor a pagar de R$ 245.760,00. O revisor confirma que o status e o valor são registrados na folha-cabeçalho e passam a alimentar a emissão de boleto, e que nenhuma linha de folha é persistida.",
"INT-040": "Com o valor de R$ 245.760,00 processado, a plataforma envia a instrução de cobrança ao gateway. O revisor confirma que retorna um boleto registrado com metadados (nosso número, vencimento, linha digitável) e link, vinculado à folha da competência. Ele confirma que a plataforma não executa nem custodia recursos — apenas solicita e registra (ADR 0003).",
"INT-041": "Assim que o boleto registrado retorna do gateway, a beneficiária Alfa acessa o portal e encontra o boleto (link e metadados) vinculado à folha da competência 08/2026. O revisor confirma a disponibilização e que nenhuma linha de folha é persistida.",
"INT-042": "O job agendado recebe do gateway o lote incremental de movimentações bancárias e casa o pagamento de R$ 245.760,00 com o boleto da Alfa 08/2026. O revisor confirma que a folha avança automaticamente para \"pago/identificado\" e que a plataforma não executa nem custodia recursos — a conciliação é só casamento/registro (ADR 0003).",
"INT-043": "Identificado o pagamento da Alfa (PAT), o motor calcula o rateio entre facilitadora, governo/MTE e demais partes, aplicando o teto de MDR de 3,6% e o prazo de repasse de até 15 dias; para a Boutique Beta (não-PAT), o revisor confirma a ramificação distinta. Ele confirma que o motor apenas calcula e aplica o split — a liquidação é do gateway (ADR 0003).",
"INT-044": "Calculado o split da Alfa, o revisor confirma que a plataforma registra o racional completo (datas, percentuais aplicados, valores por parte, ordens de transferência) como trilha auditável e entrega as ordens de transferência ao gateway via MuleSoft. Ele confirma que a plataforma não executa nem custodia recursos — apenas entrega as ordens (ADR 0003).",
"INT-045": "Concluído o repasse da folha 08/2026 da Alfa, o revisor confirma que a folha exibe \"crédito concedido\" em uma única linha consolidada (não por trabalhador), que a empresa é notificada e que a \"expectativa de crédito\" é enviada ao trabalhador via CTPS Digital. Ele confirma que nenhuma linha de folha é persistida (header/competência apenas) e que o MVP faz apenas monitoramento.",
}

data = json.loads(INTENTS.read_text(encoding="utf-8"))
updated, missing = [], []
ids_seen = {i["id"] for i in data["intents"]}
for iid in NEW:
    if iid not in ids_seen:
        missing.append(iid)
for intent in data["intents"]:
    if intent["id"] in NEW:
        intent["acceptance"] = NEW[intent["id"]]
        updated.append(intent["id"])

if missing:
    print("ERROR: ids not found in intents.json:", missing, file=sys.stderr)
    sys.exit(1)

INTENTS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"updated {len(updated)} acceptances:", ", ".join(sorted(updated)))
